name: Esegui Script Python per Aggiornare Dati EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno a mezzanotte UTC
  push:
    branches:
      - main  # Trigger quando fai push sul branch main

jobs:
  update-dati:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dal repository
    - name: Checkout codice
      uses: actions/checkout@v2  # Ottieni il codice dalla tua repository

    # Impostare Python
    - name: Impostare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Imposta la versione di Python (puoi usare 3.x per l'ultima versione)

    # Installazione delle dipendenze Python
    - name: Installare dipendenze
      run: |
        python -m pip install --upgrade pip  # Aggiorna pip
        pip install -r requirements.txt  # Installa le dipendenze dal file requirements.txt

    # Installa Chrome e ChromeDriver
    - name: Installa Chrome e ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/

    # Esegui lo script di scraping
    - name: Esegui il codice di scraping
      run: |
        python scraping.py  # Assicurati che il nome del tuo script sia corretto

    # Aggiungi e Pusha il risultato
    - name: Aggiungi e Pusha il risultato
      run: |
        git config --global user.name "GitHub Actions"  # Configura il nome utente
        git config --global user.email "actions@github.com"  # Configura l'email
        git add dati_programmi.json  # Aggiungi il file JSON generato
        git commit -m "Aggiorna i dati EPG"  # Crea un commit
        git push  # Esegui il push delle modifiche
