name: Esegui Script Python per Aggiornare Dati EPG

on:
  schedule:
    # Esegui alle 23:00 UTC (00:00 ora italiana in inverno)
    - cron: '0 23 * * *'  # Esegui ogni giorno alle 23:00 UTC
    # Esegui alle 05:00 UTC (06:00 ora italiana in inverno)
    - cron: '0 5 * * *'  # Esegui ogni giorno alle 05:00 UTC
  push:
    branches:
      - main  # Trigger quando fai push sul branch main

jobs:
  update-dati:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dal repository
    - name: Checkout codice
      uses: actions/checkout@v2  # Ottieni il codice dalla repository

    # Impostare Python
    - name: Impostare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Imposta la versione di Python (puoi usare 3.x per l'ultima versione)

    # Installazione delle dipendenze (opzionale)
    - name: Installare dipendenze
      run: |
        python -m pip install --upgrade pip  # Aggiorna pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Installa dipendenze solo se il file esiste

    # Esegui lo script di scraping
    - name: Esegui il codice di scraping
      run: |
        if [[ "${{ github.event.schedule }}" == "0 23 * * *" ]]; then
          echo "Eseguendo scraping per ieri..."
          python scraping.py --data-ieri
        elif [[ "${{ github.event.schedule }}" == "0 5 * * *" ]]; then
          echo "Eseguendo scraping per oggi..."
          python scraping.py --data-oggi
        fi

    # Aggiungi e Pusha il risultato (sempre, anche se non ci sono modifiche)
    - name: Aggiungi e Pusha il risultato
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Aggiungi i file modificati
        git add dati_programmi.json
        
        # Commit solo se ci sono modifiche
        if git diff --cached --quiet; then
          echo "Nessuna modifica nei dati. Nessun commit necessario."
        else
          git commit -m "Aggiorna i dati EPG"
          git push
        fi
