name: Esegui Script Python per Aggiornare Dati EPG

on:
  schedule:
    # Esegui alle 22:00 UTC per ottenere i dati di ieri
    - cron: '0 23 * * *'
    # Esegui alle 04:00 UTC per ottenere i dati di oggi
    - cron: '0 5 * * *'

  push:
    branches:
      - main  # Trigger quando fai push sul branch main

jobs:
  update-dati:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dal repository
    - name: Checkout codice
      uses: actions/checkout@v2

    # Impostare Python
    - name: Impostare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Installazione delle dipendenze
    - name: Installare dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Esegui lo script di scraping
    - name: Esegui il codice di scraping
      run: |
        current_time=$(date -u +"%H")
        if [ "$current_time" -eq 23 ]; then
          echo "Esecuzione dello scraping per ieri"
          python scraping.py --data-ieri
        elif [ "$current_time" -eq 5 ]; then
          echo "Esecuzione dello scraping per oggi"
          python scraping.py --data-oggi
        fi

    # Aggiungi e Pusha il risultato
    - name: Aggiungi e Pusha il risultato
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add dati_programmi.json
        git commit -m "Aggiorna i dati EPG" || echo "Nessuna modifica da commettere"
        git push
