name: Esegui scraping EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno a mezzanotte UTC
  push:
    branches:
      - main  # Trigger quando fai push su branch main

jobs:
  run-scraping:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout del repository
    - name: Checkout codice
      uses: actions/checkout@v2
      
    # Impostazione di Python
    - name: Impostare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Usa la versione Python che preferisci
    
    # Installazione delle dipendenze
    - name: Installare dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Esegui lo script di scraping
    - name: Esegui lo script di scraping
      run: |
        python tuo_script.py  # Assicurati che il nome del tuo script sia corretto
    
    # Carica i risultati (opzionale, se vuoi salvare il file JSON su GitHub)
    - name: Aggiungi e Pusha il risultato
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add programmazioni_rai_premium.json
        git commit -m "Aggiorna i dati EPG"
        git push
